const baseAPI_url = 'https://us-central1-weatherapi-27c06.cloudfunctions.net/api/weather';
const list_province = [
  'Aceh',
  'Bali',
  'BangkaBelitung',
  'Banten',
  'Bengkulu',
  'DIYogyakarta',
  'DKIJakarta',
  'Gorontalo',
  'Jambi',
  'JawaBarat',
  'JawaTengah',
  'JawaTimur',
  'KalimantanBarat',
  'KalimantanSelatan',
  'KalimantanTengah',
  'KalimantanTengah',
  'KepulauanRiau',
  'Lampung',
  'Maluku',
  'MalukuUtara',
  'NusaTenggaraBarat',
  'NusaTenggaraTimur',
  'Papua',
  'PapuaBarat',
  'Riau',
  'SulawesiBarat',
  'SulawesiSelatan',
  'SulawesiTengah',
  'SulawesiTenggara',
  'SulawesiUtara',
  'SumateraBarat',
  'SumateraSelatan',
  'SumateraUtara',
];

export { baseAPI_url, list_province };
